BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "urls" (
	"url_id"	INTEGER NOT NULL,
	"url"	TEXT NOT NULL UNIQUE,
	"short_code"	INTEGER NOT NULL UNIQUE,
	"create_at"	TEXT NOT NULL,
	"update_at"	TEXT NOT NULL,
	"clicks"	INTEGER NOT NULL,
	PRIMARY KEY("url_id" AUTOINCREMENT)
);
COMMIT;
